### ISSUE TITLE
react 支持

### ISSUE THREAD

**Issue by fantasticit** [worktile/plait#231]
请问如何在  react 中使用？
也可以提供思路。

**Comment by pubuzhixing8** [comment]
你好， @fantasticit 
我和朋友接下来准备尝试支持 react，想问下你是否还有兴趣一起参与讨论、贡献
欢迎加入 tm: https://t.me/plaitboard

**Comment by pubuzhixing8** [comment]
初步讨论：https://github.com/worktile/plait/discussions/705

**Comment by pubuzhixing8** [comment]
#905

**Comment by pubuzhixing8** [comment]
@fantasticit React 支持已经完成

**Comment by fantasticit** [comment]
Nice job. 说实话，我没看懂 plait 核心，所以没敢参与开发。
