### ISSUE TITLE
新年好，回环线支持的不是很好

### ISSUE THREAD

**Issue by aokaywe** [worktile/plait#756]
目前效果如下，会贴边显示回环线

![image](https://github.com/worktile/plait/assets/19823829/30ca8569-dfc3-401e-bb27-965b09d86d6e)

@pubuzhixing8

**Comment by pubuzhixing8** [comment]
@aokaywe 可以具体说明下，正确的期望值吗？

**Comment by aokaywe** [comment]
@pubuzhixing8 我看了其他几个软件的处理

1. draw.io

![image](https://github.com/worktile/plait/assets/19823829/f6b4e431-a6b2-4593-824a-e5aaf192c82c)

2. processon

![image](https://github.com/worktile/plait/assets/19823829/220a4e36-28a8-4c21-8f9e-84aed3d751bb)

**Comment by pubuzhixing8** [comment]
@aokaywe 我理解了，就是自己连接自己的场景

**Comment by pubuzhixing8** [comment]
已经修复：
<img width="1624" alt="Screen Shot 2024-04-02 at 14 25 44" src="https://github.com/worktile/plait/assets/18631804/7889113b-744b-4de5-9bc3-7160f36ea7a9">
